# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the docs/ directory with MkDocs
# Your documentation will be built with `mkdocs build`
# Read the Docs will find your configuration file automatically
mkdocs:
  configuration: mkdocs.yml

# Install dependencies from requirements.txt
python:
  install:
    - requirements: requirements.txt 