site_name: Woburn Hydrogeology Data
site_description: A comprehensive resource for the Woburn Massachusetts groundwater contamination site
site_author: Prof. Norman L. Jones
site_url: https://ce547.groups.et.byu.net/woburn/

repo_name: njones61/woburn
repo_url: https://github.com/njones61/woburn

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

nav:
  - Home: index.md
  - Brief History: briefhistory.md
  - Virtual Tour: tour/index.md
  - Well Logs: welllogs/index.md
  - GeoTrans: geotrans/index.md
  - Digital Maps: maps/index.md
  - Precipitation Data: precip/index.md
  - USGS Study: usgs/index.md
  - NUS Data: nus/index.md
  - Photo Gallery: photos/index.md
  - Links: links.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true 