site_name: Woburn Hydrogeology Data
site_description: A comprehensive resource for the Woburn Massachusetts groundwater contamination site
site_author: Prof. Norman L. Jones
site_url: https://ce547.groups.et.byu.net/woburn/

repo_name: njones61/woburn
repo_url: https://github.com/njones61/woburn

theme: readthedocs

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Brief History: briefhistory.md
  - Virtual Tour: tour/index.md
  - Well Logs: welllogs/index.md
  - GeoTrans: geotrans/index.md
  - Digital Maps: maps/index.md
  - Precipitation Data: precip/index.md
  - USGS Study: usgs/index.md
  - NUS Data: nus/index.md
  - Photo Gallery: photos/index.md
  - Links: links.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true 